version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.1

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack

  publish:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - orb-tools/publish:
          orb_name: monte-carlo/mc-prevent-orb
          vcs_type: << pipeline.project.type >>
          requires:
            - orb-tools/lint
            - orb-tools/pack
          context: orb-publishing
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
